name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      publish_to_test_pypi:
        description: "Publish to TestPyPI?"
        required: true
        type: choice
        options:
          - "yes"
          - "no"
        default: "no"
      publish_to_pypi:
        description: "Publish to PyPI?"
        required: true
        type: choice
        options:
          - "yes"
          - "no"
        default: "no"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          poetry install --no-interaction
      
      - name: Run tests
        run: |
          poetry run pytest tests/

      - name: Build package
        run: |
          poetry build
      
      - name: Store the distribution packages
        uses: actions/upload-artifact@v5
        with:
          name: python-package-distributions
          path: dist/
      
  publish-to-pypi:
    name: Publish Package to Pypi
    if: github.event.inputs.publish_to_pypi == 'yes'
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/graylog_api_client

    permissions:
      id-token: write

    steps:
        - name: Download all the dists
          uses: actions/download-artifact@v6
          with:
            name: python-package-distributions
            path: dist/
        - name: Publish Package to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1


  publish-to-testpypi:
    name: Publish Package to TestPyPI
    if: github.event.inputs.publish_to_test_pypi == 'yes'
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/github_api_client

    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v6
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish Package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/